language: sh

sudo: false

os:
  - linux
  - osx


addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shellcheck; fi

before_script:
  - curl -L https://api.github.com/repos/kward/shunit2/tarball 
  - mkdir shunit2 && tar -xzf tarball -C shunit2 --strip-components 1 
  - rm tarball

script:
  - shellcheck os_info.sh
  - shellcheck test.sh
  - bash test.sh