language: sh

sudo: false

os:
  - linux
  - osx

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shellcheck; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir shunit2 && curl -LO https://api.github.com/repos/kward/shunit2/tarball && cat tarball && mv tarball tarball.gz && gunzip tarball.gz && tar -xzf tarball -C shunit2 --strip-components 1 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir shunit2 && curl -L https://api.github.com/repos/kward/shunit2/tarball | tar -xz -C shunit2 --strip-components 1 ; fi

script:
  - shellcheck os_info.sh
  - shellcheck test.sh
  - bash test.sh