language: sh

sudo: false

os:
  - linux
  - osx

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shellcheck; fi

script:
  - shellcheck os_info.sh
  - shellcheck test.sh
  - bash test.sh